create table t_user
(
    id       int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    username text unique not null,
    password text        not null,
    email    text unique not null,
    role     varchar
);

create table t_project
(
    project_id   int primary key generated by default as identity,
    user_id      int references t_user (id) on delete set null,
    title        text,
    description  text,
    text_project text
);

create table t_file
(
    file_id        int primary key generated by default as identity,
    project_ref_id int references t_project (project_id) on delete set null,
    file_name      varchar,
    file_path      varchar,
    file           bytea
);

drop table t_project;
drop table t_user;